version: '3'
networks: 
  cecochat-test:
services:
  cassandra0:
    image: cassandra:4.1.3
    container_name: cecochat-test-cassandra0
    hostname: cassandra0
    networks:
      - cecochat-test
    ports:
      - "9042:9042"
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      CASSANDRA_SEEDS: "cassandra0"
      CASSANDRA_CLUSTER_NAME: cecochat-test
      CASSANDRA_DC: Europe
      CASSANDRA_RACK: Rack0
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
      HEAP_NEWSIZE: 128M
      MAX_HEAP_SIZE: 512M
